import type { QuestionCache } from './types';

export const PRELOADED_QUESTIONS: QuestionCache = {
  generales: [
    "Si pudieras tener una cena con tres personas, vivas o muertas, ¿a quiénes elegirías y por qué?",
    "¿Cuál es el mejor consejo que has recibido en tu vida?",
    "¿Qué es algo que la gente se sorprendería de saber sobre ti?",
    "Si el dinero no fuera un problema, ¿a qué te dedicarías?",
    "¿Cuál es tu recuerdo más feliz?",
    "¿Qué habilidad te gustaría dominar?",
    "¿Cuál es el libro o la película que más te ha impactado?",
    "¿Qué es lo que más valoras en una amistad?",
    "Si pudieras vivir en cualquier lugar del mundo, ¿dónde sería?",
    "¿Cuál es la lección más importante que te ha enseñado la vida hasta ahora?",
    "¿Qué es algo que te apasiona y de lo que podrías hablar durante horas?",
    "¿Cuál es tu forma favorita de pasar un fin de semana?",
    "Si tuvieras que describir tu personalidad con un tipo de clima, ¿cuál sería?",
    "¿Qué es lo más espontáneo que has hecho últimamente?",
    "¿Hay alguna causa social que te importe especialmente?",
    "¿Qué te hace sentir más vivo/a?",
    "¿Cuál es el concierto o evento en vivo más memorable al que has asistido?",
    "Si pudieras aprender cualquier idioma al instante, ¿cuál elegirías?",
    "¿Qué pequeño placer te alegra el día?",
    "¿Cómo te gusta relajarte después de un día estresante?",
    "¿Cuál es tu estación del año favorita y por qué?",
    "¿Qué es algo que siempre has querido hacer pero aún no has tenido la oportunidad?",
    "¿Qué tipo de música escuchas para subirte el ánimo?",
    "¿Cuál es la comida que podrías comer una y otra vez sin cansarte?",
    "¿Qué es algo que te hace reír a carcajadas?",
    "Si tuvieras que elegir un lema para tu vida, ¿cuál sería?",
    "¿Qué es algo que has aprendido recientemente?",
    "¿Prefieres la ciudad, el campo o la costa?",
    "¿Qué es algo que te da curiosidad?",
    "¿Qué es lo que más admiras en otras personas?",
    "¿Cuál es tu talento oculto?",
    "¿Qué es algo por lo que te sientes agradecido/a hoy?",
    "¿Qué es lo primero que haces por la mañana?",
    "Si pudieras tener cualquier trabajo por un día, ¿cuál sería?",
    "¿Qué es algo que te pone nervioso/a?",
    "¿Cuál es tu lugar favorito en tu casa?",
    "¿Qué te inspira?",
    "¿Qué significa el éxito para ti?",
    "¿Cuál es tu tradición familiar favorita?",
    "¿Qué es lo más amable que alguien ha hecho por ti?",
    "¿Cómo describirías a tu mejor amigo/a?",
    "¿Qué es algo que te gustaría que más gente supiera sobre ti?",
    "¿Eres más una persona de mañanas o de noches?",
    "¿Cuál es el mejor regalo que has dado?",
    "¿Qué es algo que te hace sentir orgulloso/a de ti mismo/a?",
    "¿Cuál es tu forma favorita de ejercitarte?",
    "¿Qué es lo que más te gusta de la tecnología?",
    "¿Y lo que menos te gusta?",
    "¿Qué es un pequeño lujo que te permites de vez en cuando?",
    "¿Qué es algo que te gustaría inventar?",
    "¿Cuál es tu festividad favorita?",
    "¿Qué es algo que te gustaría cambiar en tu comunidad?",
    "¿Cuál es el cumplido más bonito que has recibido?",
    "¿Qué es algo que te da esperanza?",
    "¿Qué te gusta hacer en un día lluvioso?",
    "¿Cuál es el documental más interesante que has visto?",
    "¿Qué es algo que te gustaría que te enseñaran en la escuela?",
    "¿Cómo te mantienes motivado/a?",
    "¿Qué es algo que te parece sobrevalorado?",
    "¿Y algo que te parece infravalorado?",
    "¿Cuál es tu flor o planta favorita?",
    "¿Qué es algo que te asusta pero que te gustaría intentar?",
    "¿Qué es lo que más te gusta de tu ciudad?",
    "¿Cuál es tu podcast o canal de YouTube favorito?",
    "¿Cómo sería tu día perfecto?",
    "¿Qué es algo que te ayuda a ser creativo/a?",
    "¿Qué es algo que has hecho que nunca pensaste que harías?",
    "¿Qué es algo que te gustaría que la gente recordara de ti?",
    "¿Prefieres leer un libro físico o en formato digital?",
    "¿Cuál es tu cita o refrán favorito?",
    "¿Qué es algo que te hace sentir nostálgico/a?",
    "¿Cuál es tu forma favorita de ayudar a los demás?",
    "¿Qué es algo que has construido o creado con tus propias manos?",
    "¿Cuál es el mejor consejo de viaje que podrías dar?",
    "¿Qué es algo que coleccionas?",
    "¿Qué es algo que te hace sentir en paz?",
    "¿Cuál es el último acto de bondad que presenciaste?",
    "¿Qué es algo que siempre llevas contigo?",
    "¿Qué es algo que te gustaría que la gente se preguntara más a menudo?",
    "¿Cuál es tu forma de arte favorita (música, pintura, cine, etc.)?",
    "¿Qué es algo que aprendiste de la manera difícil?",
    "¿Qué es algo que te hace sentir optimista sobre el futuro?",
    "¿Cuál es tu bebida favorita (caliente o fría)?",
    "¿Qué es algo que te gustaría que pasara en la próxima década?",
    "¿Cómo te desconectas del mundo digital?",
    "¿Cuál es tu juego de mesa o de cartas favorito?",
    "¿Qué es algo que te gustaría que fuera socialmente más aceptado?",
    "¿Qué es algo que te hace único/a?",
    "¿Cuál es el obstáculo más grande que has superado?",
    "¿Qué es algo que te hace sentir como en casa?",
    "¿Qué es algo que te gustaría lograr en el próximo año?",
    "¿Cuál es tu forma favorita de empezar una conversación?",
    "¿Qué es algo que te gustaría que la gente entendiera mejor?",
    "¿Cuál es tu superhéroe favorito y por qué?",
    "¿Qué es algo que te hace sentir valiente?",
    "¿Qué es algo que has perdonado?",
    "¿Cuál es el mejor evento deportivo al que has asistido?",
    "¿Qué es algo que te hace sentir conectado/a con la naturaleza?"
  ],
  profundas: [
    "¿Crees en el destino o en el libre albedrío?",
    "¿Qué significa para ti tener una vida exitosa?",
    "¿Cuál es tu mayor miedo y cómo lo enfrentas?",
    "¿Qué es algo que te gustaría cambiar de ti mismo?",
    "¿Cómo defines la felicidad?",
    "¿Crees que la humanidad está progresando o retrocediendo?",
    "¿Cuál es el propósito de la vida, según tú?",
    "¿Qué es el amor verdadero para ti?",
    "Si pudieras saber la verdad absoluta sobre una cosa, ¿qué preguntarías?",
    "¿Cómo te gustaría ser recordado?",
    "¿Qué creencia fundamental tuya ha cambiado con el tiempo?",
    "¿Cómo te ha cambiado tu mayor fracaso?",
    "¿Qué significa para ti la vulnerabilidad?",
    "¿Crees que es más importante ser respetado o ser amado?",
    "¿Qué legado te gustaría dejar?",
    "¿De qué te arrepientes más en la vida y qué aprendiste de ello?",
    "¿Qué es lo que más te asusta del futuro?",
    "¿Cómo manejas la soledad?",
    "¿Cuál es la decisión más difícil que has tenido que tomar?",
    "¿Qué te hace sentir verdaderamente realizado/a?",
    "¿Qué es algo que has sacrificado por otra persona?",
    "¿Crees que la gente puede cambiar de verdad?",
    "¿Qué significa la integridad para ti?",
    "¿Qué es algo que perdonarías difícilmente?",
    "¿Cuál es la mentira más grande que te has dicho a ti mismo/a?",
    "¿Cómo encuentras paz en un mundo caótico?",
    "¿Qué te ha enseñado el dolor?",
    "¿Crees en una segunda oportunidad?",
    "¿Qué es más importante: la intención o el resultado?",
    "¿Cómo defines tu identidad?",
    "¿Qué es algo que la sociedad valora pero que a ti no te importa?",
    "¿Cuál es la conversación más importante que has tenido?",
    "¿Qué te hace sentir inseguro/a?",
    "¿Cómo ha afectado tu pasado a la persona que eres hoy?",
    "¿Qué es algo que das por sentado y no deberías?",
    "¿Crees que es mejor conocer una verdad dolorosa o vivir en una mentira feliz?",
    "¿Qué es el alma para ti?",
    "¿Cómo cultivas el amor propio?",
    "¿Qué significa para ti ser auténtico?",
    "¿Cuál es tu opinión sobre la muerte?",
    "¿Qué es algo que has aprendido de alguien mucho más joven que tú?",
    "¿Y de alguien mucho mayor?",
    "¿Qué te impide ser completamente tú mismo/a?",
    "¿Cómo sabes que estás enamorado/a?",
    "¿Qué es la sabiduría y cómo se consigue?",
    "¿Qué batalla interna estás librando actualmente?",
    "¿Qué significa para ti la libertad?",
    "¿Has sentido alguna vez una conexión con el universo?",
    "¿Qué es algo que te rompió el corazón?",
    "¿Cómo te enfrentas a la crítica?",
    "¿Qué es más difícil: empezar algo nuevo o terminar algo viejo?",
    "¿Qué es algo que la gente malinterpreta de ti?",
    "¿Crees que el ser humano es bueno por naturaleza?",
    "¿Qué te ha enseñado tu momento más oscuro?",
    "¿Qué es algo que sabes que es verdad en lo más profundo de tu ser?",
    "¿Cuál es tu mayor conflicto interno?",
    "¿Qué es el poder y quién debería tenerlo?",
    "¿Cómo te gustaría que evolucionara la sociedad?",
    "¿Qué es algo por lo que estarías dispuesto/a a morir?",
    "¿Crees que la vida tiene un guion escrito?",
    "¿Qué es algo que te ha hecho cuestionar todo lo que creías saber?",
    "¿Cómo defines la confianza?",
    "¿Qué es el hogar para ti?",
    "¿Qué es algo que te gustaría que tus padres entendieran sobre ti?",
    "¿Qué es el mal?",
    "¿Cómo te reconcilias con las partes de ti que no te gustan?",
    "¿Qué es algo que solo compartirías con alguien en quien confías plenamente?",
    "¿Qué es lo que más te conmueve hasta las lágrimas?",
    "¿Cómo te ha cambiado una experiencia cercana a la muerte (tuya o de otro)?",
    "¿Qué es algo que te da una perspectiva diferente de la vida?",
    "¿Crees que es posible la felicidad eterna?",
    "¿Qué es el ego y cómo lo gestionas?",
    "¿Qué es algo que te hace sentir pequeño/a (en el buen sentido)?",
    "¿Qué es la justicia para ti?",
    "¿Qué significa envejecer con gracia?",
    "¿Qué es lo que más te importa al final del día?",
    "¿Qué es algo que la gente persigue pero que no trae la felicidad?",
    "¿Cómo encuentras significado en el sufrimiento?",
    "¿Qué es algo que te gustaría haber entendido antes?",
    "¿Qué es la empatía y por qué es importante?",
    "¿Qué es lo más valiente que has hecho?",
    "¿Qué te hace sentir conectado/a con otras personas?",
    "¿Cómo te ha afectado la pérdida de un ser querido?",
    "¿Qué es algo que te gustaría que la próxima generación hiciera mejor?",
    "¿Qué es el perdón y a quién beneficia más?",
    "¿Qué es algo que te hace sentir humilde?",
    "¿Qué es la intuición para ti y confías en ella?",
    "¿Qué es algo que has aceptado sobre la vida que antes te costaba?",
    "¿Cómo ha evolucionado tu concepto de amor?",
    "¿Qué significa para ti vivir una vida con propósito?",
    "¿Qué es algo que te gustaría que la gente valorara más?",
    "¿Qué es la soledad y es siempre algo malo?",
    "¿Qué te hace sentir verdaderamente agradecido/a por estar vivo/a?",
    "¿Qué es algo que te ha enseñado a ser más compasivo/a?",
    "¿Qué es lo que más te enorgullece de tu carácter?",
    "¿Qué es la conciencia?"
  ],
  divertidas: [
    "Si fueras un superhéroe, ¿cuál sería tu superpoder y tu nombre de héroe?",
    "¿Cuál es la cosa más extraña que has comido?",
    "Si los animales pudieran hablar, ¿cuál sería el más grosero?",
    "¿Qué canción te sabes de memoria y te da vergüenza admitir?",
    "¿Cuál es tu anécdota más vergonzosa?",
    "Si tu vida fuera una película, ¿qué género sería y quién te interpretaría?",
    "¿Qué harías si te encontraras con un zombi en el supermercado?",
    "¿Cuál es el objeto más inútil que posees pero que te encanta?",
    "Si pudieras intercambiar tu vida con un personaje de dibujos animados, ¿quién serías?",
    "¿Qué es lo más ridículo por lo que has discutido con alguien?",
    "¿Cuál es tu 'spirit animal' y por qué?",
    "Si tuvieras que comer lo mismo todos los días durante un año, ¿qué comida elegirías?",
    "¿Cuál es el peor corte de pelo que has tenido?",
    "¿Qué es lo más raro que has buscado en Google?",
    "Si pudieras poner una regla tonta que todo el mundo tuviera que seguir, ¿cuál sería?",
    "¿Cuál es tu talento inútil?",
    "¿Qué personaje de ficción sería el peor compañero de piso?",
    "Si fueras un sabor de helado, ¿cuál serías?",
    "¿Cuál es la moda más ridícula que has seguido?",
    "¿Qué harías si fueras invisible por un día?",
    "¿Cuál es el apodo más raro que te han puesto?",
    "Si pudieras tener una banda sonora para tu vida, ¿qué tres canciones incluiría?",
    "¿Cuál es el chiste más malo que te sabes?",
    "Si tuvieras que describir tu sentido del humor en tres palabras, ¿cuáles serían?",
    "¿Qué es lo más raro que has comprado online?",
    "¿Cuál es tu movimiento de baile característico?",
    "Si pudieras ser un experto instantáneo en algo trivial, ¿qué sería?",
    "¿Cuál es la combinación de comida más extraña que te gusta?",
    "¿Qué es algo que hacías de niño/a y que ahora te parece rarísimo?",
    "Si tu casa estuviera en llamas y solo pudieras salvar un objeto no esencial, ¿cuál sería?",
    "¿Qué es lo más divertido que has visto hacer a un extraño en público?",
    "Si tuvieras una advertencia en la frente, ¿qué diría?",
    "¿Cuál es la peor película que has visto hasta el final?",
    "Si pudieras hablar con tu mascota, ¿cuál sería la primera pregunta que le harías?",
    "¿Qué es lo más estúpido que has hecho por seguir una tendencia?",
    "Si te arrestaran sin explicación, ¿qué pensarían tus amigos que hiciste?",
    "¿Cuál es la palabra que siempre pronuncias mal?",
    "Si pudieras reemplazar los apretones de manos con otro gesto, ¿cuál sería?",
    "¿Qué es algo que a todo el mundo le encanta y a ti no te gusta?",
    "¿Cuál es el sueño más absurdo que recuerdas haber tenido?",
    "Si tuvieras que vivir dentro de un programa de televisión, ¿cuál sería?",
    "¿Qué es lo más vergonzoso que han encontrado en tu teléfono?",
    "¿Cuál sería el título de tu autobiografía?",
    "Si pudieras añadir una asignatura al currículum escolar, ¿cuál sería?",
    "¿Qué es lo más raro que te ha pasado en una cita?",
    "Si los objetos de tu habitación pudieran hablar, ¿cuál contaría la mejor historia?",
    "¿Cuál es la excusa más creativa que has usado para llegar tarde?",
    "Si tu coche pudiera hablar, ¿qué diría de ti?",
    "¿Qué es lo más infantil que todavía haces?",
    "¿Cuál es el peor regalo que has recibido?",
    "Si tuvieras que crear un nuevo día festivo, ¿cuál sería?",
    "¿Qué es algo que finges saber pero que no tienes ni idea?",
    "¿Cuál es la cosa más extraña que llevas en tu bolso o mochila ahora mismo?",
    "Si pudieras tener la voz de cualquier persona, ¿quién elegirías?",
    "¿Cuál es la teoría de conspiración más divertida que has escuchado?",
    "Si pudieras hacer una pregunta a cualquier animal, ¿a cuál y qué le preguntarías?",
    "¿Qué es lo más raro que te has encontrado en el bolsillo de un abrigo viejo?",
    "Si tuvieras que crear un nuevo sabor de patatas fritas, ¿cuál sería?",
    "¿Qué es algo que te da mucha pereza hacer?",
    "¿Cuál es la peor canción para poner en una boda?",
    "Si tu risa tuviera un sonido, ¿cuál sería?",
    "¿Qué es lo más loco que has hecho para conseguir Wi-Fi gratis?",
    "¿Cuál es el superpoder más inútil que se te ocurre?",
    "Si fueras un mueble, ¿cuál serías y por qué?",
    "¿Qué es lo más competitivo que haces?",
    "¿Cuál es el rumor más gracioso que has iniciado o escuchado?",
    "Si tuvieras que usar un disfraz todos los días durante un mes, ¿cuál elegirías?",
    "¿Qué es algo que te encantaba de niño/a y ahora odias?",
    "¿Cuál es la app más inútil de tu teléfono?",
    "Si pudieras tener un robot para una sola tarea, ¿cuál sería?",
    "¿Qué es lo más raro que has hecho estando solo/a en casa?",
    "¿Cuál es tu placer culpable en YouTube o TikTok?",
    "Si tuvieras que describir el último año con un título de película, ¿cuál sería?",
    "¿Qué es algo que te irrita irracionalmente?",
    "¿Cuál es la peor moda que recuerdas?",
    "Si pudieras hacer que un alimento no tuviera calorías, ¿cuál sería?",
    "¿Qué es lo más raro que has visto en la casa de otra persona?",
    "¿Qué harías si te quedaras atrapado/a en un ascensor con tu jefe?",
    "¿Cuál es la peor compra que has hecho?",
    "Si tuvieras que ser un personaje secundario en una película, ¿quién serías?",
    "¿Qué es lo más gracioso que has leído en un baño público?",
    "¿Cuál es tu emoji más usado?",
    "Si pudieras tener un eslogan personal, ¿cuál sería?",
    "¿Qué es algo que haces que sabes que molesta a los demás pero no puedes evitarlo?",
    "¿Cuál es el nombre más raro que le pondrías a una mascota?",
    "Si tuvieras que rapear sobre tu vida, ¿cuál sería la primera línea?",
    "¿Qué es lo más extraño que has usado como marcador de libros?",
    "¿Cuál es la mentira más tonta que has contado?",
    "Si fueras un fantasma, ¿a quién te gustaría asustar?",
    "¿Qué es lo más raro que has soñado que comías?",
    "¿Cuál sería tu nombre de luchador/a profesional?",
    "Si tuvieras que narrar la vida de alguien, ¿a quién elegirías?",
    "¿Qué es lo más raro que te ha dicho un niño?",
    "¿Cuál es el sonido que más odias?",
    "Si tuvieras que reemplazar tu mano con un objeto, ¿cuál sería?"
  ],
  hipoteticas: [
    "Si pudieras viajar en el tiempo, ¿irías al pasado o al futuro?",
    "Si tuvieras la capacidad de ser invisible por un día, ¿qué harías?",
    "Si pudieras hablar con tu yo de 10 años, ¿qué consejo le darías?",
    "Si te dieran tres deseos, ¿qué pedirías?",
    "Si pudieras eliminar una palabra del diccionario, ¿cuál sería y por qué?",
    "Si tuvieras que vivir en un videojuego durante un mes, ¿cuál elegirías?",
    "Si pudieras tener cualquier animal como mascota, real o fantástico, ¿cuál sería?",
    "Si pudieras resolver un misterio sin resolver del mundo, ¿cuál sería?",
    "Si pudieras aprender a hacer algo instantáneamente, ¿qué sería?",
    "Si mañana despertaras con una nueva habilidad o talento, ¿cuál te gustaría que fuera?",
    "Si pudieras tener una conversación de 30 minutos con cualquier persona en la historia, ¿quién sería y qué le preguntarías?",
    "Si pudieras diseñar el planeta perfecto, ¿qué tres cosas tendría?",
    "Si te ofrecieran la inmortalidad, ¿la aceptarías? ¿Por qué sí o por qué no?",
    "Si pudieras saber la fecha exacta de tu muerte, ¿querrías saberla?",
    "Si tuvieras que renunciar a uno de tus cinco sentidos, ¿cuál sería?",
    "Si pudieras vivir en el universo de cualquier libro o película, ¿cuál elegirías?",
    "Si solo pudieras escuchar a un artista musical por el resto de tu vida, ¿quién sería?",
    "Si pudieras tener la respuesta a una pregunta sobre el universo, ¿qué preguntarías?",
    "Si pudieras intercambiar vidas con alguien por un día, ¿con quién sería?",
    "Si pudieras respirar bajo el agua, ¿qué es lo primero que explorarías?",
    "Si pudieras crear una ley universal que todos tuvieran que obedecer, ¿cuál sería?",
    "Si pudieras tener el trabajo de tus sueños, pero nunca ser reconocido/a por él, ¿lo aceptarías?",
    "Si pudieras hablar todos los idiomas del mundo, ¿qué harías con esa habilidad?",
    "Si solo pudieras comer un tipo de cocina por el resto de tu vida, ¿cuál sería?",
    "Si pudieras tener una casa en cualquier lugar del mundo (real o ficticio), ¿dónde estaría?",
    "Si pudieras detener el tiempo por una hora cada día, ¿cómo usarías esa hora?",
    "Si pudieras tener una cena con cinco personajes de ficción, ¿a quiénes invitarías?",
    "Si pudieras ser inmune a una cosa, ¿qué elegirías?",
    "Si pudieras cambiar un evento de la historia, ¿cuál sería y por qué?",
    "Si tuvieras la habilidad de entender a los animales, ¿qué harías?",
    "Si tuvieras que elegir una década para vivir, ¿cuál sería?",
    "Si pudieras tener un mentor de cualquier campo, ¿quién sería?",
    "Si tuvieras que abandonar tu país, ¿a dónde te mudarías?",
    "Si pudieras tener un objeto de cualquier película, ¿cuál sería?",
    "Si tuvieras que describir la humanidad a un extraterrestre con una sola palabra, ¿cuál sería?",
    "Si pudieras tener una banda sonora personal que sonara de fondo, ¿qué tipo de música sería?",
    "Si pudieras asegurarte el éxito en una sola cosa, ¿qué elegirías?",
    "Si pudieras hacer que todo el mundo leyera un libro, ¿cuál sería?",
    "Si pudieras tener los recuerdos de otra persona, ¿a quién elegirías?",
    "Si tuvieras que vivir sin internet o sin tu teléfono, ¿qué elegirías?",
    "Si pudieras rediseñar el cuerpo humano, ¿qué cambio harías?",
    "Si pudieras tener un clon de ti mismo/a, ¿qué le encargarías hacer?",
    "Si pudieras tener un encuentro pacífico con una especie extraterrestre, ¿qué les preguntarías?",
    "Si tuvieras que elegir entre tener más tiempo o más dinero, ¿qué preferirías?",
    "Si pudieras borrar un recuerdo de tu mente, ¿cuál sería?",
    "Si pudieras tener la habilidad de teletransportarte, pero solo a lugares en los que ya has estado, ¿a dónde irías primero?",
    "Si tuvieras que vivir en una colonia en Marte, ¿qué tres objetos personales te llevarías?",
    "Si pudieras saber lo que la gente realmente piensa de ti, ¿querrías saberlo?",
    "Si pudieras tener un día perfecto, ¿qué incluiría?",
    "Si tuvieras que crear un nuevo color, ¿cómo lo llamarías y cómo sería?",
    "Si pudieras dar un consejo a toda la humanidad, ¿cuál sería?",
    "Si pudieras volver a experimentar algo por primera vez, ¿qué sería?",
    "Si tuvieras que elegir un solo recuerdo para conservar por la eternidad, ¿cuál sería?",
    "Si pudieras predecir el futuro, ¿lo usarías para tu beneficio o para el de los demás?",
    "Si tuvieras que elegir entre no volver a escuchar música o no volver a ver películas, ¿qué elegirías?",
    "Si pudieras tener una conversación con tu futuro yo, ¿qué le preguntarías?",
    "Si tuvieras que pasar un año en completo aislamiento, ¿qué tres libros te llevarías?",
    "Si pudieras tener cualquier tipo de vista desde tu ventana, ¿cuál sería?",
    "Si tuvieras la oportunidad de ser el primer ser humano en contactar con vida inteligente, ¿qué dirías?",
    "Si pudieras hacer que una especie extinguida volviera a la vida, ¿cuál sería?",
    "Si pudieras tener una habilidad de un videojuego en la vida real, ¿cuál sería?",
    "Si tuvieras que vivir el mismo día una y otra vez, ¿qué harías para no aburrirte?",
    "Si pudieras saber la respuesta a cualquier pregunta, pero solo una, ¿qué preguntarías?",
    "Si tuvieras que renunciar a las comidas dulces o saladas para siempre, ¿cuáles elegirías?",
    "Si pudieras tener el control sobre tus sueños, ¿qué soñarías esta noche?",
    "Si pudieras resolver un gran problema mundial, ¿cuál sería?",
    "Si pudieras tener una conversación con el océano, ¿qué le preguntarías?",
    "Si tuvieras que elegir un poder de la naturaleza para controlar, ¿cuál sería (viento, agua, fuego, tierra)?",
    "Si pudieras cambiar el final de una película, ¿cuál sería y cómo terminaría?",
    "Si tuvieras que comer nubes o beber arcoíris, ¿qué elegirías?",
    "Si pudieras tener una habilidad artística que no tienes, ¿cuál sería?",
    "Si pudieras fusionar dos animales para crear uno nuevo, ¿cuáles serían?",
    "Si tuvieras que vivir sin uno de los colores, ¿cuál sacrificarías?",
    "Si pudieras tener una conversación con una planta, ¿qué le preguntarías?",
    "Si pudieras saber instantáneamente si alguien está mintiendo, ¿usarías esa habilidad?",
    "Si tuvieras que elegir un personaje histórico para ser tu compañero de piso, ¿quién sería?",
    "Si pudieras tener un portal a otro lugar en tu armario, ¿a dónde te gustaría que llevara?",
    "Si pudieras entender el lenguaje de la programación universalmente, ¿qué crearías?",
    "Si tuvieras que elegir entre la capacidad de volar o la de leer mentes, ¿cuál preferirías?",
    "Si pudieras vivir en una casa del árbol de lujo o en una cueva moderna, ¿qué elegirías?",
    "Si tuvieras que elegir un solo recuerdo para proyectar en el cielo para que todos lo vieran, ¿cuál sería?",
    "Si pudieras tener un botón de 'deshacer' en la vida real, ¿con qué frecuencia lo usarías?",
    "Si pudieras traer un personaje de un libro a la vida real, ¿quién sería?",
    "Si tuvieras que crear un nuevo planeta, ¿qué nombre le pondrías?",
    "Si pudieras saber qué canción se queda atascada en la cabeza de la gente, ¿qué harías con esa información?",
    "Si tuvieras que comunicarte solo con emojis durante 24 horas, ¿cómo te las arreglarías?",
    "Si pudieras tener la habilidad de hacer crecer plantas instantáneamente, ¿qué harías?",
    "Si tuvieras que elegir una criatura mítica para que fuera real, ¿cuál sería?",
    "Si pudieras tener una vista de pájaro de cualquier momento de la historia, ¿cuál elegirías?",
    "Si pudieras vivir en un mundo sin mentiras, ¿sería mejor o peor?",
    "Si tuvieras que elegir una canción para que sonara cada vez que entras en una habitación, ¿cuál sería?",
    "Si pudieras tener un debate con cualquier figura histórica, ¿con quién y sobre qué tema?",
    "Si tuvieras que renunciar a las redes sociales o a los servicios de streaming, ¿qué elegirías?",
    "Si pudieras hacer que la lluvia supiera a algo, ¿qué sabor elegirías?",
    "Si pudieras tener un compañero animal parlante, ¿qué animal sería?",
    "Si tuvieras que elegir entre nunca volver a sentir tristeza o nunca volver a sentir alegría, ¿qué preferirías?"
  ],
  picantes: [
    "¿Cuál es el lugar más atrevido donde has tenido una cita?",
    "¿Qué es lo más loco que has hecho por amor o atracción?",
    "¿Cuál es tu mayor 'placer culpable'?",
    "¿Qué es algo que te parece secretamente atractivo en otra persona?",
    "Describe tu cita perfecta y atrevida.",
    "¿Crees en el amor a primera vista o en la lujuria a primera vista?",
    "¿Cuál es la mentira más grande que has dicho y te has salido con la tuya?",
    "Si pudieras hacer una pregunta indiscreta a cualquiera y obtener una respuesta honesta, ¿a quién y qué preguntarías?",
    "¿Qué es lo más espontáneo que has hecho?",
    "¿Cuál es el rumor más divertido que has escuchado sobre ti?",
    "¿Cuál ha sido el sueño más extraño o atrevido que has tenido?",
    "¿Qué es lo primero en lo que te fijas en una persona que te atrae?",
    "¿Alguna vez has enviado un mensaje a la persona equivocada? ¿Cuál fue el resultado?",
    "¿Cuál es la excusa más creativa que has usado para cancelar un plan?",
    "¿Qué es algo que nunca le contarías a tus padres?",
    "¿Cuál es tu opinión sobre las relaciones abiertas?",
    "¿Qué es más importante en una pareja: el sentido del humor o la inteligencia?",
    "¿Alguna vez has tenido un flechazo con alguien completamente inesperado?",
    "¿Qué canción te pone de humor 'picante'?",
    "¿Cuál es tu opinión sobre los besos en la primera cita?",
    "¿Qué es lo más atrevido que has publicado en redes sociales?",
    "¿Cuál es el piropo más original que has recibido o dado?",
    "¿Alguna vez has fingido que te gusta algo solo para impresionar a alguien?",
    "¿Qué es algo que te da vergüenza admitir que te gusta?",
    "Describe un beso memorable.",
    "¿Qué es algo que la gente piensa que es romántico pero a ti no te lo parece?",
    "¿Cuál es el secreto más grande que has guardado?",
    "¿Has tenido alguna vez un amor platónico por un profesor o jefe?",
    "¿Qué es lo más lejos que has llegado en un juego de 'verdad o reto'?",
    "¿Cuál es tu celebrity crush (amor platónico famoso)?",
    "¿Qué es algo que te gustaría probar pero te da miedo?",
    "¿Cuál es la nota más atrevida que has escrito o recibido?",
    "¿Alguna vez has espiado el teléfono de tu pareja?",
    "¿Qué es algo que te hace sentir sexy?",
    "¿Cuál es tu opinión sobre las aplicaciones de citas?",
    "¿Qué es lo más atrevido que has llevado puesto?",
    "¿Alguna vez has tenido una cita a ciegas? ¿Cómo fue?",
    "¿Qué es algo que te pone celoso/a irracionalmente?",
    "¿Cuál es la fantasía más común que crees que tiene la gente?",
    "¿Qué es lo más embarazoso que te ha pasado durante un momento romántico?",
    "¿Crees que es posible mantener una amistad con derechos sin que nadie salga herido?",
    "¿Qué es algo que te excita que no es sexual?",
    "¿Cuál es el apodo más cursi que le has puesto a una pareja?",
    "¿Alguna vez has interrumpido un momento íntimo de otra persona por accidente?",
    "¿Qué es algo que encuentras irresistible?",
    "¿Cuál es tu opinión sobre enviar fotos atrevidas?",
    "¿Qué es lo más rebelde que hiciste en tu adolescencia?",
    "¿Prefieres una relación apasionada y tumultuosa o una tranquila y estable?",
    "¿Qué es algo que te gustaría que tu pareja hiciera más a menudo?",
    "¿Cuál es la peor frase para ligar que has escuchado?",
    "¿Alguna vez has escrito una carta de amor?",
    "¿Qué es algo que te hace sonrojar?",
    "¿Cuál es el mayor riesgo que has tomado en el amor?",
    "¿Qué es lo más importante en la química entre dos personas?",
    "¿Has roto con alguien por mensaje de texto?",
    "¿Qué es algo que te parece un 'red flag' (señal de alarma) inmediato en una cita?",
    "¿Cuál es el personaje de ficción que te parece más atractivo?",
    "¿Qué es algo que has hecho para llamar la atención de alguien que te gustaba?",
    "¿Cuál es tu película romántica favorita (o la que más odias)?",
    "¿Has tenido alguna vez un 'casi algo' que te marcó?",
    "¿Qué es algo que te parece más íntimo que el sexo?",
    "¿Cuál es el secreto para mantener viva la chispa en una relación larga?",
    "¿Alguna vez has fingido un orgasmo?",
    "¿Qué es algo que te da curiosidad sobre el sexo opuesto?",
    "¿Cuál es tu opinión sobre el matrimonio?",
    "¿Qué es lo más romántico que has hecho por alguien?",
    "¿Alguna vez te has enamorado de un amigo/a cercano/a?",
    "¿Qué es algo que te parece un 'turn-on' (algo que te excita) instantáneo?",
    "¿Y un 'turn-off' (algo que te desanima) instantáneo?",
    "¿Cuál es el mejor lugar para una primera cita?",
    "¿Has tenido alguna vez una experiencia paranormal de tipo romántico?",
    "¿Qué es algo que te gustaría que la gente fuera más honesta al respecto?",
    "¿Cuál es la parte del cuerpo que te resulta más atractiva?",
    "¿Alguna vez has tenido un sueño con alguien de esta sala?",
    "¿Qué es algo que te gustaría que estuviera socialmente aceptado en las citas?",
    "¿Cuál es tu opinión sobre las demostraciones públicas de afecto?",
    "¿Has vuelto alguna vez con un ex?",
    "¿Qué es algo que te haría terminar una relación al instante?",
    "¿Cuál es la diferencia entre amar a alguien y estar enamorado de alguien?",
    "¿Qué es lo más valiente que has hecho en una relación?",
    "¿Alguna vez has tenido un presentimiento sobre alguien y acertaste?",
    "¿Qué es algo que te gustaría que la gente supiera sobre las relaciones?",
    "¿Cuál es tu recuerdo más romántico?",
    "¿Crees en las almas gemelas?",
    "¿Qué es lo más loco que has hecho para superar una ruptura?",
    "¿Cuál es el gesto de amor más pequeño pero más significativo?",
    "¿Alguna vez has tenido una relación secreta?",
    "¿Qué es algo que te gustaría que te preguntaran en una cita?",
    "¿Cuál es tu lenguaje del amor?",
    "¿Has stalkeado a un ex en redes sociales?",
    "¿Qué es algo que te gustaría que fuera diferente en la cultura de las citas actual?",
    "¿Cuál es la decisión más impulsiva que has tomado por amor?",
    "¿Qué es algo que te parece sexy pero que a la mayoría de la gente no?",
    "¿Alguna vez has dicho 'te quiero' y no lo sentías?",
    "¿Qué es algo que has aprendido sobre ti mismo/a a través de tus relaciones?",
    "¿Cuál es la aventura de una noche más memorable que has tenido?",
    "¿Qué es algo que te hace sentir vulnerable en una relación?",
    "¿Cuál es tu mayor fantasía romántica?"
  ],
  filosoficas: [
    "¿Es posible la objetividad, o todo es subjetivo?",
    "Si un árbol cae en un bosque y no hay nadie para oírlo, ¿hace ruido?",
    "¿Qué es más importante: la felicidad o el propósito?",
    "¿La tecnología nos une o nos aísla más?",
    "¿Se puede justificar una mala acción si el resultado es bueno?",
    "¿Qué define la conciencia humana?",
    "¿La libertad es una ilusión?",
    "¿Tenemos la obligación moral de ayudar a los demás?",
    "¿Qué es la belleza y quién la define?",
    "¿Puede existir la moral sin la religión?",
    "¿Qué es la justicia?",
    "¿Nacemos con una esencia o la creamos a lo largo de nuestra vida?",
    "¿Es el sufrimiento necesario para el crecimiento personal?",
    "¿Cómo sabes que lo que percibes como realidad es real?",
    "¿Podría una máquina tener conciencia?",
    "¿Qué significa ser una 'buena persona'?",
    "¿El fin justifica los medios?",
    "¿Es la naturaleza humana inherentemente buena o mala?",
    "¿Qué es el arte y cuál es su propósito?",
    "¿Qué es la verdad?",
    "¿Es el conocimiento poder?",
    "¿Qué es el tiempo?",
    "Si tuvieras una copia exacta de ti mismo, ¿sería esa copia 'tú'?",
    "¿Qué es la nada?",
    "¿Por qué hay algo en lugar de nada?",
    "¿Tienen los animales derechos?",
    "¿Qué es la mente?",
    "¿Es la matemática un invento o un descubrimiento?",
    "¿Cuál es la relación entre el lenguaje y el pensamiento?",
    "¿Qué es el infinito?",
    "¿Puede la lógica resolver todos los problemas?",
    "¿Qué es la suerte?",
    "¿Es la ética universal o relativa a cada cultura?",
    "¿Qué es una sociedad ideal?",
    "¿Tenemos libre albedrío si nuestras acciones pueden ser predichas por la neurociencia?",
    "¿Qué es la identidad personal y cómo se mantiene a lo largo del tiempo?",
    "¿Es la búsqueda de la felicidad un objetivo egoísta?",
    "¿Qué es la normalidad?",
    "¿Es posible vivir una vida sin hacer daño a otros?",
    "¿Qué es la fe?",
    "¿Cuál es el valor del arte en la sociedad?",
    "¿Debería la ciencia tener límites?",
    "¿Qué es la amistad?",
    "¿Qué es más real, el mundo físico o el mundo de las ideas?",
    "¿Qué es la utopía y es alcanzable?",
    "¿Qué es la tradición y qué valor tiene?",
    "¿Es la guerra una parte inevitable de la naturaleza humana?",
    "¿Qué es la cultura?",
    "¿Qué es la felicidad sin la tristeza?",
    "¿Podemos confiar en nuestros sentidos?",
    "¿Qué es el genio?",
    "¿Cuál es el propósito de la educación?",
    "¿Es la privacidad un derecho fundamental?",
    "¿Qué es la igualdad?",
    "¿Qué es la inteligencia artificial y qué significa para la humanidad?",
    "¿Qué es el bien común?",
    "¿Es la venganza justificable en alguna circunstancia?",
    "¿Qué es la sabiduría?",
    "¿Qué es la intuición?",
    "¿Qué es el honor?",
    "¿Puede una idea ser peligrosa?",
    "¿Qué es la autenticidad?",
    "¿Qué es el progreso?",
    "¿Qué es la paciencia?",
    "¿Es la simplicidad la clave de la felicidad?",
    "¿Qué es la creatividad?",
    "¿Qué es la muerte y debemos temerla?",
    "¿Qué es la imaginación?",
    "¿Qué es la esperanza?",
    "¿Qué es el coraje?",
    "¿Cuál es el papel del individuo en la sociedad?",
    "¿Es la historia cíclica?",
    "¿Qué es la compasión?",
    "¿Qué es la memoria y cuán fiable es?",
    "¿Qué es el lenguaje?",
    "¿Es la naturaleza caótica o está ordenada?",
    "¿Qué es la percepción?",
    "¿Qué es la inspiración?",
    "¿Qué es el humor y por qué nos reímos?",
    "¿Qué es el poder?",
    "¿Qué es el silencio?",
    "¿Qué es la armonía?",
    "¿Qué es la virtud?",
    "¿Qué es el sacrificio?",
    "¿Qué es la trascendencia?",
    "¿Qué es la comunidad?",
    "¿Qué es el destino?",
    "¿Qué es la casualidad?",
    "¿Qué es la empatía?",
    "¿Qué es el conocimiento de uno mismo?",
    "¿Qué es la civilización?",
    "¿Qué es la anarquía?",
    "¿Qué es el nihilismo?",
    "¿Qué es el existencialismo?",
    "¿Qué es el estoicismo?",
    "¿Qué es el hedonismo?",
    "¿Qué es el altruismo?"
  ],
  viajes: [
    "¿Cuál es el destino de tus sueños y por qué?",
    "¿Prefieres viajar solo, en pareja o en grupo?",
    "¿Playa o montaña? ¿Por qué?",
    "¿Cuál es la comida más exótica que has probado en un viaje?",
    "Cuenta una anécdota divertida o inesperada de uno de tus viajes.",
    "Si tuvieras que mudarte a un país en el que nunca has estado, ¿cuál elegirías?",
    "¿Qué es lo más importante que empacas en tu maleta?",
    "¿Prefieres un viaje lleno de aventuras o uno de relajación total?",
    "¿Cuál es el lugar más impresionante que has visitado?",
    "¿Qué has aprendido sobre ti mismo viajando?",
    "¿Qué es lo más valioso que has aprendido al viajar?",
    "¿Prefieres los destinos turísticos populares o los lugares escondidos?",
    "¿Cuál es la cultura más diferente a la tuya que has experimentado?",
    "¿Qué souvenir te gusta coleccionar de tus viajes?",
    "Si tuvieras que hacer un viaje por carretera, ¿qué ruta elegirías y con quién irías?",
    "¿Cuál es el medio de transporte más extraño que has usado?",
    "Describe un amanecer o atardecer inolvidable que hayas visto en un viaje.",
    "¿Te consideras un planificador de viajes o un viajero espontáneo?",
    "¿Qué es lo que más te estresa de viajar?",
    "¿Cuál es el mejor consejo de viaje que has recibido?",
    "¿Hotel, hostal o Airbnb?",
    "¿Cuál es el paisaje que más te ha dejado sin aliento?",
    "¿Has tenido alguna vez una mala experiencia de viaje que ahora te parezca graciosa?",
    "¿Qué es lo que más extrañas de casa cuando viajas?",
    "¿Cuál es el idioma más difícil que has intentado hablar en un viaje?",
    "¿Prefieres viajar con mochila o con maleta?",
    "¿Cuál es la ciudad que más te ha sorprendido?",
    "¿Qué es algo que siempre haces cuando visitas un lugar nuevo?",
    "¿Has hecho algún viaje que te haya cambiado la vida?",
    "¿Cuál es el monumento más sobrevalorado que has visitado?",
    "¿Y el más infravalorado?",
    "¿Qué tipo de música escuchas cuando viajas?",
    "¿Prefieres un viaje a una gran metrópolis o a un pequeño pueblo?",
    "¿Qué es lo más aventurero que has hecho en un viaje?",
    "¿Cuál es el recuerdo más preciado que tienes de un viaje?",
    "¿Qué es algo que te asusta de viajar?",
    "¿Cómo te comunicas en un país donde no hablas el idioma?",
    "¿Cuál es el festival o evento cultural más interesante al que has asistido?",
    "¿Qué es lo que más te gusta de volver a casa después de un viaje?",
    "¿Cuál es el próximo destino en tu lista?",
    "¿Qué es algo que has aprendido sobre otra cultura que te ha sorprendido?",
    "¿Prefieres un viaje de verano o de invierno?",
    "¿Cuál es el mejor recuerdo de un viaje familiar?",
    "¿Has viajado alguna vez por trabajo? ¿Te gusta?",
    "¿Qué es lo más raro que has comido en la calle?",
    "¿Cuál es tu película de viajes favorita?",
    "¿Te gusta visitar museos cuando viajas?",
    "¿Cuál es la compra más interesante que has hecho en un viaje?",
    "¿Has sentido alguna vez el 'choque cultural inverso' al volver a casa?",
    "¿Qué es algo que te gustaría que tu ciudad tuviera de otros lugares que has visitado?",
    "¿Cuál es el viaje más largo que has hecho?",
    "¿Prefieres explorar la naturaleza o las ciudades?",
    "¿Has tenido alguna vez una conexión especial con un lugar?",
    "¿Qué es lo más importante que has aprendido sobre la planificación de viajes?",
    "¿Has conocido a gente interesante mientras viajabas?",
    "¿Cuál es el mercado local más fascinante que has visitado?",
    "¿Te gusta probar el transporte público local?",
    "¿Qué es algo que siempre te olvidas de empacar?",
    "¿Has hecho voluntariado en el extranjero?",
    "¿Cuál es tu forma favorita de documentar tus viajes (fotos, diario, blog)?",
    "¿Qué es lo más romántico que te ha pasado en un viaje?",
    "¿Has tenido algún encuentro con animales salvajes?",
    "¿Cuál es el mejor recuerdo de un viaje con amigos?",
    "¿Te gusta perderte en una ciudad nueva?",
    "¿Qué es algo que te ha hecho sentir humilde mientras viajabas?",
    "¿Cuál es el mejor libro que has leído durante un viaje?",
    "¿Has visitado algún lugar por una película o libro?",
    "¿Qué es algo que te gustaría que la gente supiera sobre tu país?",
    "¿Cuál es el lugar más remoto al que has viajado?",
    "¿Prefieres un guía turístico o explorar por tu cuenta?",
    "¿Qué es algo que te ha decepcionado de un destino?",
    "¿Has superado algún miedo durante un viaje?",
    "¿Cuál es el mejor recuerdo gastronómico de un viaje?",
    "¿Te gusta viajar en tren?",
    "¿Qué es algo que te ha enseñado a ser más paciente mientras viajas?",
    "¿Cuál es el lugar al que siempre volverías?",
    "¿Has tenido alguna vez problemas en un aeropuerto?",
    "¿Qué es lo que más te gusta de la comida de avión (o lo que menos)?",
    "¿Cuál es el mejor consejo para superar el jet lag?",
    "¿Te gusta aprender frases básicas del idioma local?",
    "¿Qué es algo que te ha hecho sentir fuera de tu zona de confort?",
    "¿Cuál es el viaje más barato que has hecho?",
    "¿Y el más caro?",
    "¿Has visitado alguna maravilla del mundo?",
    "¿Qué es lo que más te inspira a viajar?",
    "¿Cómo eliges tu próximo destino?",
    "¿Qué es algo que te gustaría que fuera más fácil al viajar?",
    "¿Has acampado alguna vez en un lugar exótico?",
    "¿Cuál es el mejor recuerdo de un viaje por carretera?",
    "¿Qué es lo que más te emociona de planificar un nuevo viaje?",
    "¿Has tenido alguna vez una epifanía mientras viajabas?",
    "¿Qué es algo que solo puedes experimentar en un lugar específico?",
    "¿Cuál es el recuerdo más divertido de perderte en un lugar?",
    "¿Qué es lo que más te gusta de experimentar una nueva cultura?",
    "¿Cómo te ha cambiado viajar como persona?",
    "Si tuvieras un año sabático, ¿a dónde irías?"
  ],
  carrera: [
    "¿Qué querías ser de mayor cuando eras niño?",
    "Si pudieras cambiar de profesión por un día, ¿qué harías?",
    "¿Cuál es el mayor desafío que has enfrentado en tu carrera?",
    "¿Qué es lo que más te apasiona de tu trabajo?",
    "¿Cómo mides el éxito profesional?",
    "¿Cuál es el mejor consejo profesional que has recibido?",
    "Si pudieras tener un mentor, ¿quién sería?",
    "¿Qué habilidad crees que es crucial para el futuro del trabajo?",
    "¿Prefieres trabajar en una oficina o de forma remota?",
    "¿Qué es algo que has aprendido de un fracaso en el trabajo?",
    "¿Qué es más importante para ti en un trabajo: un buen sueldo o la satisfacción personal?",
    "Describe tu ambiente de trabajo ideal.",
    "¿Cuál ha sido tu mayor logro profesional hasta ahora?",
    "¿Cómo te mantienes motivado/a en el trabajo?",
    "Si pudieras iniciar tu propio negocio, ¿de qué sería?",
    "¿Qué piensas sobre la idea de tener un solo trabajo para toda la vida?",
    "¿Cuál es la lección más importante que has aprendido de un jefe o colega?",
    "¿Cómo manejas el estrés laboral?",
    "¿Qué es algo que desearías haber sabido al principio de tu carrera?",
    "¿Prefieres trabajar solo/a o en equipo?",
    "¿Cuál es la parte más gratificante de tu trabajo?",
    "¿Y la más frustrante?",
    "¿Cómo encuentras el equilibrio entre la vida laboral y personal?",
    "¿Qué es algo que te gustaría automatizar en tu trabajo?",
    "Si tuvieras que dar una charla TED sobre tu campo, ¿cuál sería el tema?",
    "¿Qué es algo que te gustaría aprender para mejorar en tu carrera?",
    "¿Cuál es tu opinión sobre las reuniones de trabajo?",
    "¿Qué es algo que te hace sentir productivo/a?",
    "¿Cómo te enfrentas a las críticas constructivas?",
    "¿Qué es algo que admiras en un líder?",
    "Si pudieras cambiar algo de tu industria, ¿qué sería?",
    "¿Cuál es el mayor riesgo profesional que has tomado?",
    "¿Cómo celebras tus éxitos profesionales?",
    "¿Qué es algo que te ayuda a concentrarte?",
    "¿Cuál es tu opinión sobre el 'networking'?",
    "¿Qué es algo que te gustaría que tu empresa hiciera de manera diferente?",
    "¿Cómo te mantienes actualizado/a en tu campo?",
    "¿Cuál es la herramienta o software sin el que no podrías vivir en tu trabajo?",
    "¿Qué es algo que te gustaría que la gente entendiera sobre tu profesión?",
    "¿Has tenido algún trabajo 'raro' o inusual?",
    "¿Cuál es el mejor cumplido que has recibido en el trabajo?",
    "¿Cómo manejas los conflictos con tus compañeros?",
    "¿Qué es algo que te gustaría que se valorara más en el entorno laboral?",
    "¿Cuál es tu rutina de trabajo diaria?",
    "¿Qué es algo que te da energía durante la jornada laboral?",
    "¿Has pensado alguna vez en un cambio radical de carrera?",
    "¿Qué es algo que has aprendido de tu peor jefe?",
    "¿Cuál es la entrevista de trabajo más extraña que has tenido?",
    "¿Qué es algo que te gustaría enseñar a otros sobre tu trabajo?",
    "¿Cómo te preparas para una presentación importante?",
    "¿Qué es algo que te parece una pérdida de tiempo en el trabajo?",
    "¿Cuál es tu opinión sobre la semana laboral de cuatro días?",
    "¿Qué es algo que te gustaría que tus compañeros supieran de ti?",
    "¿Cómo te desconectas del trabajo al final del día?",
    "¿Qué es algo que te ha sorprendido de tu trayectoria profesional?",
    "¿Cuál es el mejor consejo para alguien que empieza en tu campo?",
    "¿Qué es algo que te gustaría lograr en los próximos cinco años?",
    "¿Has tenido un 'momento eureka' en el trabajo?",
    "¿Qué es algo que te hace sentir valorado/a en tu trabajo?",
    "¿Cómo manejas la procrastinación?",
    "¿Qué es algo que te gustaría que fuera diferente en la cultura laboral en general?",
    "¿Cuál es tu opinión sobre los ascensos y la jerarquía?",
    "¿Qué es algo que te gustaría que tu jefe supiera?",
    "¿Cómo te adaptas a los cambios en el trabajo?",
    "¿Qué es algo que te hace sentir orgulloso/a de tu empresa o equipo?",
    "¿Cuál es tu podcast o libro de desarrollo profesional favorito?",
    "¿Qué es algo que te gustaría que se midiera más en el rendimiento laboral además de los resultados?",
    "¿Cómo te mantienes creativo/a en tu trabajo?",
    "¿Qué es algo que te gustaría que tus clientes o usuarios supieran?",
    "¿Has tenido alguna vez el síndrome del impostor? ¿Cómo lo manejas?",
    "¿Qué es algo que te gustaría que fuera más flexible en tu trabajo?",
    "¿Cuál es tu opinión sobre la inteligencia artificial en tu sector?",
    "¿Qué es algo que te gustaría que se reconociera más en tu profesión?",
    "¿Cómo te enfrentas a un día poco productivo?",
    "¿Qué es algo que te gustaría que cambiara en las entrevistas de trabajo?",
    "¿Cuál es tu opinión sobre los beneficios y ventajas laborales?",
    "¿Qué es algo que te gustaría que la educación preparara mejor para el mundo laboral?",
    "¿Cómo te recuperas de un error en el trabajo?",
    "¿Qué es algo que te gustaría que la gente dejara de decir sobre tu profesión?",
    "¿Cuál es tu forma favorita de tomar un descanso en el trabajo?",
    "¿Qué es algo que te gustaría que tus subordinados supieran, si los tuvieras?",
    "¿Cómo te mantienes positivo/a ante los desafíos laborales?",
    "¿Qué es algo que te gustaría que se celebrara más en el trabajo?",
    "¿Cuál es tu opinión sobre el 'trabajo apasionado'?",
    "¿Qué es algo que te gustaría que la gente joven supiera sobre el mundo laboral?",
    "¿Cómo te defines profesionalmente en una frase?",
    "¿Qué es algo que te gustaría que la gente entendiera sobre el liderazgo?",
    "¿Cuál es el mejor equipo en el que has trabajado y por qué?",
    "¿Qué es algo que te gustaría que la tecnología resolviera en tu trabajo?",
    "¿Cómo te aseguras de seguir aprendiendo y creciendo profesionalmente?",
    "¿Qué es algo que te gustaría que la gente preguntara más en el trabajo?",
    "¿Cuál es tu visión del futuro del trabajo?",
    "¿Qué es algo que te gustaría que tus estudios te hubieran preparado mejor?",
    "¿Cómo te motivas para hacer las tareas que no te gustan?",
    "¿Qué es algo que te gustaría que la sociedad valorara más que el trabajo?",
    "¿Qué es lo más importante que has aprendido sobre el dinero?",
    "¿Cuál es tu objetivo profesional final?"
  ],
  recuerdos: [
    "¿Cuál es tu primer recuerdo de la infancia?",
    "¿A qué juego te encantaba jugar cuando eras niño?",
    "¿Quién era tu héroe de la infancia?",
    "¿Cuál era tu comida favorita cuando eras pequeño?",
    "¿Cuál es la mayor travesura que hiciste de niño?",
    "¿Qué recuerdo te hace reír siempre que piensas en él?",
    "¿Cuál era tu programa de televisión o película favorita de niño?",
    "¿Tienes algún recuerdo especial de las vacaciones en familia?",
    "¿Qué es algo que extrañas de ser un niño?",
    "¿Qué lección de tu infancia todavía aplicas hoy?",
    "¿Cuál es el olor que más te transporta a tu infancia?",
    "¿Cuál fue el mejor regalo que recibiste cuando eras niño/a?",
    "¿Recuerdas a tu primer mejor amigo/a? ¿Qué solían hacer?",
    "¿Cuál era tu escondite secreto cuando eras pequeño/a?",
    "¿Qué es algo que tus padres solían decirte constantemente?",
    "¿Cuál es el recuerdo más vívido que tienes de tus abuelos?",
    "¿Qué canción te recuerda a tu adolescencia?",
    "¿Cuál fue la primera película que viste en el cine?",
    "¿Qué es algo que coleccionabas de niño/a?",
    "¿Recuerdas tu primer día de colegio?",
    "¿Cuál era tu juguete favorito?",
    "¿Qué es algo que te daba mucho miedo de niño/a?",
    "¿Recuerdas alguna moda ridícula de tu juventud?",
    "¿Cuál es el mejor recuerdo que tienes de un cumpleaños?",
    "¿Qué es algo que aprendiste de tus hermanos, si los tienes?",
    "¿Cuál era tu lugar favorito para jugar al aire libre?",
    "¿Recuerdas la primera vez que te enamoraste?",
    "¿Qué es algo que te encantaba hacer en verano?",
    "¿Cuál es el recuerdo más embarazoso de tu adolescencia?",
    "¿Quién fue el profesor que más te marcó?",
    "¿Cuál era tu libro o cuento favorito?",
    "¿Qué es algo que siempre quisiste tener de niño/a y nunca tuviste?",
    "¿Recuerdas alguna fiesta de pijamas memorable?",
    "¿Cuál es el recuerdo más tonto por el que te metiste en problemas?",
    "¿Qué es algo que creías de niño/a y que resultó ser falso?",
    "¿Cuál es el mejor recuerdo de una excursión escolar?",
    "¿Qué es algo que te gustaba comer y que ahora no soportas?",
    "¿Recuerdas tu primer concierto?",
    "¿Cuál es el recuerdo más feliz que tienes con tus amigos de la infancia?",
    "¿Qué es algo que hacías para ganar dinero de bolsillo?",
    "¿Recuerdas el primer álbum de música que compraste?",
    "¿Cuál era tu apodo de niño/a?",
    "¿Qué es algo que te enseñaron tus padres y que valoras mucho?",
    "¿Recuerdas algún proyecto escolar del que te sintieras muy orgulloso/a?",
    "¿Cuál es el recuerdo más nítido que tienes de tu casa de la infancia?",
    "¿Qué es algo que te parecía mágico cuando eras pequeño/a?",
    "¿Recuerdas el primer deporte que practicaste?",
    "¿Cuál es el recuerdo más bonito de una Navidad o festividad?",
    "¿Qué es algo que te gustaría poder decirle a tu yo más joven?",
    "¿Recuerdas el primer viaje que hiciste sin tus padres?",
    "¿Cuál era tu personaje de dibujos animados preferido?",
    "¿Qué es algo que te gustaba construir o crear?",
    "¿Recuerdas el momento en que te diste cuenta de que te estabas haciendo mayor?",
    "¿Cuál es el recuerdo más valioso que tienes de un familiar que ya no está?",
    "¿Qué es algo que te hacía sentir muy valiente de niño/a?",
    "¿Recuerdas la primera vez que dormiste fuera de casa?",
    "¿Cuál es el sabor que te recuerda a tu infancia?",
    "¿Qué es algo que te gustaría que tus hijos (o futuros hijos) experimentaran de tu infancia?",
    "¿Recuerdas tu primer teléfono móvil?",
    "¿Cuál es el recuerdo más divertido de una mascota de la infancia?",
    "¿Qué es algo que te gustaba hacer en los recreos?",
    "¿Recuerdas el primer libro que te enganchó de verdad?",
    "¿Cuál es el recuerdo más importante de tu graduación?",
    "¿Qué es algo que te parecía muy difícil de niño/a y ahora es fácil?",
    "¿Recuerdas algún club o equipo al que pertenecías?",
    "¿Cuál es el recuerdo más surrealista que tienes?",
    "¿Qué es algo que te gustaba ver en la televisión después del colegio?",
    "¿Recuerdas la primera vez que cocinaste algo por ti mismo/a?",
    "¿Cuál es el recuerdo más emocionante de un parque de atracciones?",
    "¿Qué es algo que te gustaba oler?",
    "¿Recuerdas tu primer viaje en avión?",
    "¿Cuál es el recuerdo más gracioso de una confusión?",
    "¿Qué es algo que te parecía de 'adultos' cuando eras niño/a?",
    "¿Recuerdas algún sueño recurrente que tuvieras?",
    "¿Cuál es el recuerdo más bonito de un día de lluvia?",
    "¿Qué es algo que te gustaba aprender?",
    "¿Recuerdas el primer secreto que guardaste?",
    "¿Cuál es el recuerdo más entrañable de tu adolescencia?",
    "¿Qué es algo que te gustaba hacer con tus abuelos?",
    "¿Recuerdas el primer 'te quiero' que dijiste o te dijeron (no romántico)?",
    "¿Cuál es el recuerdo más memorable de un campamento de verano?",
    "¿Qué es algo que te hacía sentir especial de niño/a?",
    "¿Recuerdas tu primer ordenador o consola de videojuegos?",
    "¿Cuál es el recuerdo más bonito de un acto de bondad?",
    "¿Qué es algo que te gustaba hacer en el coche durante viajes largos?",
    "¿Recuerdas la primera vez que viste la nieve o el mar?",
    "¿Cuál es el recuerdo más importante que tienes de aprender a leer o escribir?",
    "¿Qué es algo que te gustaba de la escuela?",
    "¿Recuerdas tu primer amor platónico?",
    "¿Cuál es el recuerdo más fuerte que tienes asociado a una canción?",
    "¿Qué es algo que te parecía una gran aventura?",
    "¿Recuerdas la primera vez que te sentiste independiente?",
    "¿Cuál es el recuerdo más feliz de un día de verano?",
    "¿Qué es algo que te gustaría revivir de tu pasado?",
    "¿Recuerdas la primera vez que te diste cuenta de lo que querías ser de mayor?",
    "¿Cuál es el recuerdo más poderoso que tienes de un sonido?",
    "¿Qué es algo que te hace sonreír sin motivo aparente cuando lo recuerdas?",
    "¿Recuerdas la primera vez que te sentiste verdaderamente orgulloso/a de ti mismo/a?"
  ],
  relaciones: [
    "¿Qué cualidad valoras más en una pareja?",
    "¿Cuál crees que es el secreto para una amistad duradera?",
    "¿Qué es lo más importante que has aprendido sobre el amor?",
    "¿Cómo manejas los desacuerdos en una relación?",
    "¿Qué significa para ti la familia?",
    "¿Cuál es el gesto más romántico que alguien ha tenido contigo?",
    "¿Prefieres pasar tiempo con un gran grupo de amigos o con unos pocos amigos cercanos?",
    "¿Qué es algo que no perdonarías en una relación?",
    "¿Cómo ha cambiado tu idea del amor a lo largo de los años?",
    "¿Cuál es el mejor recuerdo que tienes con tus amigos?",
    "¿Crees que es posible ser amigo/a de un ex?",
    "¿Cuál es tu lenguaje del amor principal?",
    "¿Qué es algo que has aprendido de tus relaciones pasadas?",
    "¿Qué es un 'deal breaker' (algo inaceptable) para ti en una relación?",
    "¿Cómo demuestras aprecio a las personas que te importan?",
    "¿Cuál es el mejor consejo sobre relaciones que has recibido?",
    "¿Qué papel juega el humor en una relación para ti?",
    "¿Crees que las almas gemelas existen?",
    "¿Cómo defines la confianza en una relación?",
    "¿Qué es algo que admiras en la relación de otras personas?",
    "¿Qué es más importante en una amistad: la lealtad o la honestidad?",
    "¿Cómo sabes que puedes confiar en alguien?",
    "¿Qué es algo que te gustaría mejorar en tus relaciones?",
    "¿Cuál es la diferencia entre estar solo/a y sentirse solo/a?",
    "¿Qué es lo que más te gusta de tus amigos?",
    "¿Cómo ha influido tu familia en cómo te relacionas con los demás?",
    "¿Qué es algo que te hace sentir conectado/a con alguien?",
    "¿Cuál es la base de una relación sana para ti?",
    "¿Cómo te disculpas cuando te equivocas?",
    "¿Qué es algo que te gustaría que tus seres queridos supieran de ti?",
    "¿Crees en el amor para toda la vida?",
    "¿Qué es algo que has hecho para mantener una amistad a larga distancia?",
    "¿Cuál es el mayor sacrificio que has hecho por alguien?",
    "¿Cómo apoyas a un amigo que está pasando por un mal momento?",
    "¿Qué es algo que te ha decepcionado en una relación?",
    "¿Cómo celebras los logros de tus seres queridos?",
    "¿Qué es algo que te parece un 'green flag' (buena señal) en una persona?",
    "¿Cuál es tu opinión sobre vivir juntos antes del matrimonio?",
    "¿Qué es algo que has aprendido sobre ti mismo/a a través de una relación?",
    "¿Cómo mantienes tu independencia dentro de una pareja?",
    "¿Qué es algo que te gustaría que la gente entendiera sobre el amor?",
    "¿Cuál es el recuerdo más divertido que tienes con tu familia?",
    "¿Cómo ha evolucionado tu relación con tus padres a lo largo de los años?",
    "¿Qué es algo que te hace sentir amado/a?",
    "¿Cuál es tu opinión sobre las redes sociales y las relaciones?",
    "¿Qué es algo que te gustaría que tu pareja y tú hicierais más a menudo?",
    "¿Cómo se construye la intimidad en una relación (no solo física)?",
    "¿Qué es algo que te gustaría que tus amigos te dijeran más a menudo?",
    "¿Cuál es la lección más dura que has aprendido sobre la amistad?",
    "¿Cómo decides si vale la pena luchar por una relación?",
    "¿Qué es algo que te hace sentir orgulloso/a de tu pareja o amigo/a?",
    "¿Cuál es la tradición más importante que tienes con tus amigos o pareja?",
    "¿Qué es algo que te gustaría que la gente hiciera menos en las relaciones?",
    "¿Cómo te afecta el lenguaje del amor de otra persona si es diferente al tuyo?",
    "¿Qué es algo que te gustaría que tu familia entendiera mejor de ti?",
    "¿Cuál es el mejor viaje que has hecho con amigos o pareja?",
    "¿Cómo te comunicas cuando estás enfadado/a?",
    "¿Qué es algo que te gustaría que la gente valorara más en la amistad?",
    "¿Cuál es el papel de la vulnerabilidad en una relación?",
    "¿Qué es algo que te ha enseñado una ruptura?",
    "¿Cómo sabes que una amistad es verdadera?",
    "¿Qué es algo que te gustaría que cambiara en la forma en que la sociedad ve las relaciones?",
    "¿Cuál es el mejor regalo (no material) que te ha dado alguien?",
    "¿Cómo equilibras el tiempo para tu pareja, amigos, familia y para ti mismo/a?",
    "¿Qué es algo que te gustaría que la gente preguntara más en lugar de asumir?",
    "¿Cuál es tu recuerdo más feliz en una relación romántica?",
    "¿Cómo manejas los celos?",
    "¿Qué es algo que te gustaría que la gente supiera sobre la soltería?",
    "¿Cuál es la aventura más grande que has compartido con alguien?",
    "¿Cómo demuestras tu apoyo a los sueños de tu pareja o amigos?",
    "¿Qué es algo que te gustaría que tus relaciones futuras tuvieran?",
    "¿Cuál es tu opinión sobre las segundas oportunidades en el amor?",
    "¿Qué es algo que te hace sentir seguro/a en una relación?",
    "¿Cuál es el mejor consejo para una pareja de recién casados?",
    "¿Cómo ha afectado la tecnología a tus relaciones?",
    "¿Qué es algo que te gustaría que la gente hiciera para mostrar que le importa?",
    "¿Cuál es el mayor desafío en las relaciones hoy en día?",
    "¿Cómo te mantienes conectado/a con amigos que viven lejos?",
    "¿Qué es algo que te gustaría que la gente entendiera sobre el compromiso?",
    "¿Cuál es tu recuerdo más entrañable con un hermano/a?",
    "¿Cómo ha cambiado tu círculo de amigos con el tiempo?",
    "¿Qué es algo que te gustaría que la gente dejara de hacer en las citas?",
    "¿Cuál es el acto de amor más grande que has presenciado?",
    "¿Cómo sabes cuándo es el momento de dejar ir una relación?",
    "¿Qué es algo que te gustaría que la gente valorara más que la apariencia física?",
    "¿Cuál es tu forma favorita de pasar tiempo de calidad con alguien?",
    "¿Cómo ha influido la amistad en la persona que eres hoy?",
    "¿Qué es algo que te gustaría que la gente supiera sobre el perdón?",
    "¿Cuál es el mejor cumplido que le puedes hacer a alguien en una relación?",
    "¿Cómo defines un 'hogar' con otra persona?",
    "¿Qué es algo que te gustaría que la gente hiciera más para fortalecer sus lazos familiares?",
    "¿Cuál es la conversación más importante que crees que se debe tener en una pareja?",
    "¿Cómo ha impactado el amor en tus metas y aspiraciones?",
    "¿Qué es algo que te gustaría que la gente recordara sobre el amor y la amistad?",
    "¿Qué es lo más importante que buscas en un compañero de vida?"
  ]
};
